# Generated by Django 2.0.4 on 2018-04-14 11:59

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='balance')),
            ],
            options={
                'verbose_name': 'account',
                'verbose_name_plural': 'accounts',
                'ordering': ['affiliation'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='AccountMovement',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='balance')),
                ('account_movement_type', models.CharField(choices=[('I', 'Invoice'), ('D', 'Deposit'), ('G', 'Grand Lodge Deposit'), ('C', 'Charge')], max_length=1, verbose_name='account movement type')),
                ('object_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'account movement',
                'verbose_name_plural': 'account movements',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('charge_type', models.CharField(choices=[('I', 'Initiation'), ('P', 'Pass'), ('R', 'Raise'), ('O', 'Other')], max_length=1, verbose_name='charge type')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description.', max_length=300, verbose_name='description')),
            ],
            options={
                'verbose_name': 'charge',
                'verbose_name_plural': 'charges',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description.', max_length=300, verbose_name='description')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'deposit',
                'verbose_name_plural': 'deposits',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='GrandLodgeDeposit',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description.', max_length=300, verbose_name='description')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts', verbose_name='receipt')),
                ('status', models.CharField(blank=True, choices=[('P', 'Pending'), ('A', 'Accredited'), ('R', 'Rejected')], default='P', max_length=1, verbose_name='status')),
            ],
            options={
                'verbose_name': 'grand lodge deposit',
                'verbose_name_plural': 'grand lodge deposits',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LodgeAccount',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='description')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='balance')),
            ],
            options={
                'verbose_name': 'lodge account',
                'verbose_name_plural': 'lodge accounts',
                'ordering': ['handler'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LodgeAccountEgress',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('egress_type', models.CharField(choices=[('D', 'Donation'), ('PH', 'Philantropy'), ('E', 'Expenses'), ('L', 'Loan'), ('GLT', 'Grand Lodge Transfer'), ('O', 'Other')], max_length=3, verbose_name='egress type')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description.', max_length=300, verbose_name='description')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'lodge account egress',
                'verbose_name_plural': 'lodge account egresses',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LodgeAccountIngress',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='amount')),
                ('ingress_type', models.CharField(choices=[('D', 'Donation'), ('PH', 'Philantropy'), ('PA', 'Payment'), ('O', 'Other')], max_length=3, verbose_name='ingress type')),
                ('description', models.CharField(blank=True, default='', help_text='Optional description.', max_length=300, verbose_name='description')),
                ('receipt', models.FileField(blank=True, null=True, upload_to='receipts', verbose_name='receipt')),
            ],
            options={
                'verbose_name': 'lodge account ingress',
                'verbose_name_plural': 'lodge account ingresses',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LodgeAccountMovement',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('description', models.CharField(max_length=150, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='balance')),
                ('lodgeaccount_movement_type', models.CharField(choices=[('I', 'Ingress'), ('E', 'Egress'), ('T', 'Transfer'), ('D', 'Deposit')], max_length=1, verbose_name='lodge account movement type')),
                ('object_id', models.BigIntegerField()),
            ],
            options={
                'verbose_name': 'lodge account movement',
                'verbose_name_plural': 'lodge account movements',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LodgeAccountTransfer',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('description', models.CharField(blank=True, default='', max_length=150, verbose_name='description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='amount')),
            ],
            options={
                'verbose_name': 'lodge account transfer',
                'verbose_name_plural': 'lodge account transfers',
                'ordering': ['-created_on'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='LodgeGlobalAccount',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='balance')),
            ],
            options={
                'verbose_name': 'lodge global account',
                'verbose_name_plural': 'lodge global accounts',
                'ordering': ['lodge'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True, verbose_name='is active?')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on')),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on')),
                ('begin', models.DateField(verbose_name='begin')),
                ('end', models.DateField(verbose_name='end')),
                ('price_multiplier', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Usually the category price is defined by a single unit price, but a period may have multiple units. For example, a unit can be a month, but a period could be 3, 4 or 12 months.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='price multiplier')),
            ],
            options={
                'verbose_name': 'period',
                'verbose_name_plural': 'periods',
                'ordering': ['-begin'],
                'default_permissions': ('add', 'change', 'delete', 'view'),
            },
        ),
    ]
