# Generated by Django 2.0.4 on 2018-04-13 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('treasure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='period',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='period',
            name='lodge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', related_query_name='period', to='users.Lodge', verbose_name='lodge'),
        ),
        migrations.AddField(
            model_name='lodgeglobalaccount',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='lodgeglobalaccount',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='lodgeglobalaccount',
            name='lodge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='lodge_global_account', to='users.Lodge', verbose_name='lodge'),
        ),
        migrations.AddField(
            model_name='lodgeaccounttransfer',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='lodgeaccounttransfer',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='lodgeaccounttransfer',
            name='lodge_account_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_from', related_query_name='transfer_from', to='treasure.LodgeAccount', verbose_name='lodge account from'),
        ),
        migrations.AddField(
            model_name='lodgeaccounttransfer',
            name='lodge_account_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_to', related_query_name='transfer_to', to='treasure.LodgeAccount', verbose_name='lodge account to'),
        ),
        migrations.AddField(
            model_name='lodgeaccountmovement',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='lodgeaccountmovement',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='lodgeaccountmovement',
            name='lodge_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', related_query_name='movement', to='treasure.LodgeAccount', verbose_name='lodge account'),
        ),
        migrations.AddField(
            model_name='lodgeaccountmovement',
            name='object_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='lodgeaccountingress',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='lodgeaccountingress',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='lodgeaccountingress',
            name='lodge_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ingresses', related_query_name='ingress', to='treasure.LodgeAccount', verbose_name='lodge account'),
        ),
        migrations.AddField(
            model_name='lodgeaccountegress',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='lodgeaccountegress',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='lodgeaccountegress',
            name='lodge_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='egresses', related_query_name='egress', to='treasure.LodgeAccount', verbose_name='lodge account'),
        ),
        migrations.AddField(
            model_name='lodgeaccount',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='lodgeaccount',
            name='handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lodge_accounts', related_query_name='lodge_account', to='users.Affiliation', verbose_name='handler'),
        ),
        migrations.AddField(
            model_name='lodgeaccount',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='affiliation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', related_query_name='invoice', to='users.Affiliation', verbose_name='affiliation'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', related_query_name='invoice', to='treasure.Period', verbose_name='period'),
        ),
        migrations.AddField(
            model_name='grandlodgedeposit',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='grandlodgedeposit',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='grandlodgedeposit',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grand_lodge_deposits', related_query_name='grand_lodge_deposit', to='users.Affiliation', verbose_name='payer'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='lodge_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', related_query_name='deposit', to='treasure.LodgeAccount', verbose_name='lodge account'),
        ),
        migrations.AddField(
            model_name='deposit',
            name='payer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deposits', related_query_name='deposit', to='users.Affiliation', verbose_name='payer'),
        ),
        migrations.AddField(
            model_name='charge',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='charge',
            name='debtor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charges', related_query_name='charge', to='users.Affiliation', verbose_name='debtor'),
        ),
        migrations.AddField(
            model_name='charge',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', related_query_name='movement', to='treasure.Account', verbose_name='account'),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
        migrations.AddField(
            model_name='accountmovement',
            name='object_ct',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='account',
            name='affiliation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to='users.Affiliation', verbose_name='affiliation'),
        ),
        migrations.AddField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='account',
            name='last_modified_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.PROTECT, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL, verbose_name='last modified by'),
        ),
    ]
