# Generated by Django 2.0.5 on 2018-05-24 11:47

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'default_permissions': ('add', 'change', 'delete', 'view'), 'ordering': ['user__last_name', 'user__first_name'], 'verbose_name': 'affiliation', 'verbose_name_plural': 'affiliations'},
        ),
        migrations.AlterField(
            model_name='categoryprice',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='price'),
        ),
    ]
