# Generated by Django 2.1.7 on 2019-03-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180524_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='most_worshipful',
            field=models.BooleanField(blank=True, default=False, help_text='Is or was elected as Most Worshipful Master of the Grand Lodge.', verbose_name='most worshipful'),
        ),
        migrations.AlterField(
            model_name='user',
            name='past_master',
            field=models.BooleanField(blank=True, default=False, help_text='Is or was Worshipful Master.', verbose_name='past master'),
        ),
        migrations.AlterField(
            model_name='user',
            name='worshipful',
            field=models.BooleanField(blank=True, default=False, help_text='Is or was elected official of the Grand Lodge.', verbose_name='worshipful'),
        ),
    ]
